from django.urls import path
from django.views.generic import RedirectView
from .views import (
    CadastroView,
    ContatoView,
    DashboardView,
    InicioView,
    MetaAdicionarValorView,
    MetaCreateView,
    MetaDeleteView,
    MetaUpdateView,
    MetasView,
    MovimentacaoCreateView,
    MovimentacaoDeleteView,
    MovimentacaoDetailView,
    MovimentacaoUpdateView,
    MovimentacoesView,
    RecursosView,
    RelatoriosView,
    SaldoView,
    SobreView,
    UsuarioLoginView,
    UsuarioLogoutView,
)

urlpatterns = [
    path("inicio/", InicioView.as_view(), name="inicio"),
    path("", RedirectView.as_view(pattern_name="inicio", permanent=False)),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("movimentacoes/", MovimentacoesView.as_view(), name="movimentacoes"),
    path("movimentacoes/nova/", MovimentacaoCreateView.as_view(), name="movimentacao_nova"),
    path("movimentacoes/<int:pk>/editar/", MovimentacaoUpdateView.as_view(), name="movimentacao_editar"),
    path("movimentacoes/<int:pk>/excluir/", MovimentacaoDeleteView.as_view(), name="movimentacao_excluir"),
    path("movimentacoes/<int:pk>/", MovimentacaoDetailView.as_view(), name="movimentacao_detalhe"),
    path("metas/", MetasView.as_view(), name="metas"),
    path("metas/nova/", MetaCreateView.as_view(), name="meta_nova"),
    path("metas/<int:pk>/adicionar-valor/", MetaAdicionarValorView.as_view(), name="meta_adicionar_valor"),
    path("metas/<int:pk>/editar/", MetaUpdateView.as_view(), name="meta_editar"),
    path("metas/<int:pk>/excluir/", MetaDeleteView.as_view(), name="meta_excluir"),
    path("saldo/", SaldoView.as_view(), name="saldo"),
    path("relatorios/", RelatoriosView.as_view(), name="relatorios"),
    path("recursos/", RecursosView.as_view(), name="recursos"),
    path("sobre/", SobreView.as_view(), name="sobre"),
    path("contato/", ContatoView.as_view(), name="contato"),
    path("cadastro/", CadastroView.as_view(), name="cadastro"),
    path("logout/", UsuarioLogoutView.as_view(), name="logout"),
    path("login/", UsuarioLoginView.as_view(), name="login"),
]
